# Updated Q4 2024/Q1 2025
TREASURY_BILL_RATE = 4.5  # Update quarterly from treasury.gov
TRADING_DAYS_PER_YEAR = 252

# Portfolio constraints
WEIGHT_SUM_TOLERANCE = 1e-6
MIN_WEIGHT = 0.0
MAX_WEIGHT = 1.0

# Default values
DEFAULT_RISK_TOLERANCE = 20.0
DEFAULT_EXPECTED_RETURN = 0.25
